/**
 * Centralised icon re-exports for the public school site so pages import
 * from a single, tree-shakeable module.
 */
export {
    Languages,
    Menu,
    X,
    Search,
    ChevronDown,
    ChevronRight,
    ChevronLeft,
    ArrowRight,
    ArrowLeft,
    CalendarDays,
    CalendarClock,
    CalendarPlus,
    RotateCcw,
    GraduationCap,
    Users,
    Megaphone,
    Newspaper,
    LayoutDashboard,
    PenLine,
    Download,
    Phone,
    Mail,
    MapPin,
    Clock,
    Paperclip,
    Pin,
    FileText,
    FileSpreadsheet,
    File,
    Trophy,
    BookOpen,
    Palette,
    Volleyball,
    Bus,
    FlaskConical,
    Quote,
    Send,
    Sparkles,
    Star,
    Award,
    Target,
    Eye,
    UsersRound,
    ClipboardList,
    ThumbsUp,
    // Social (brand icons were removed from lucide — use generic marks + labels)
    Globe,
    AtSign,
    Share2,
    MessagesSquare,
    // Renamed / replacement icons
    Funnel as Filter,
    TriangleAlert as AlertTriangle,
} from '@lucide/vue';
